# Generated by Django 4.0.4 on 2023-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.CharField(max_length=100),
        ),
    ]
