# Generated by Django 4.0.4 on 2023-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forget_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
